name: SIT Server
on:
  push:
    branches: develop
  schedule:
    - cron:  '* * * * *'
jobs:
  notification:
    runs-on: self-hosted
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Send Slack notification
      uses: 8398a7/action-slack@v2
      # if: failure()
      with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.SLACK_GITHUB_TOKEN }}
